# Generated by Django 5.2 on 2025-04-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('heart', 'Heart Disease'), ('lung', 'Lung Disease'), ('liver', 'Liver Disease'), ('diabetes', 'Diabetes')], max_length=20)),
                ('risk_percentage', models.FloatField()),
                ('category', models.CharField(max_length=20)),
                ('advice', models.TextField()),
                ('input_data', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
