# Generated by Django 5.2 on 2025-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthOracle', '0002_chatbotsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotsuggestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
